version: '3'

services:
  web:
    build: . 
    command: 
      python3 ./notes_app/main.py
    ports:
      - 8000:8000
    volumes:
      - ./notes_app


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: