version: 3

services:
  web:
    build: fff #путь к докерфайлу 
    
    command: 
      python3 ./notes_app/main.py

    ports:
      - 1234:1234


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: